// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 *Ответ
 */
export class choose_sync_mode_resp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):choose_sync_mode_resp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAschoose_sync_mode_resp(bb:flatbuffers.ByteBuffer, obj?:choose_sync_mode_resp):choose_sync_mode_resp {
  return (obj || new choose_sync_mode_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAschoose_sync_mode_resp(bb:flatbuffers.ByteBuffer, obj?:choose_sync_mode_resp):choose_sync_mode_resp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new choose_sync_mode_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 *Статус, true если нет ошибок
 */
status():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 *Некорректный запрос
 */
incorrectRequest():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Внутрення ошибка ПМ Брокер сообщений, дальнейшая работа невозможна
 */
internalError():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Некорректный шаг продвижения по логическому времени
 */
incorrectDt():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startchoose_sync_mode_resp(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addStatus(builder:flatbuffers.Builder, status:boolean) {
  builder.addFieldInt8(0, +status, +true);
}

static addIncorrectRequest(builder:flatbuffers.Builder, incorrectRequest:boolean) {
  builder.addFieldInt8(1, +incorrectRequest, +false);
}

static addInternalError(builder:flatbuffers.Builder, internalError:boolean) {
  builder.addFieldInt8(2, +internalError, +false);
}

static addIncorrectDt(builder:flatbuffers.Builder, incorrectDt:boolean) {
  builder.addFieldInt8(3, +incorrectDt, +false);
}

static endchoose_sync_mode_resp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createchoose_sync_mode_resp(builder:flatbuffers.Builder, status:boolean, incorrectRequest:boolean, internalError:boolean, incorrectDt:boolean):flatbuffers.Offset {
  choose_sync_mode_resp.startchoose_sync_mode_resp(builder);
  choose_sync_mode_resp.addStatus(builder, status);
  choose_sync_mode_resp.addIncorrectRequest(builder, incorrectRequest);
  choose_sync_mode_resp.addInternalError(builder, internalError);
  choose_sync_mode_resp.addIncorrectDt(builder, incorrectDt);
  return choose_sync_mode_resp.endchoose_sync_mode_resp(builder);
}

unpack(): choose_sync_mode_respT {
  return new choose_sync_mode_respT(
    this.status(),
    this.incorrectRequest(),
    this.internalError(),
    this.incorrectDt()
  );
}


unpackTo(_o: choose_sync_mode_respT): void {
  _o.status = this.status();
  _o.incorrectRequest = this.incorrectRequest();
  _o.internalError = this.internalError();
  _o.incorrectDt = this.incorrectDt();
}
}

export class choose_sync_mode_respT {
constructor(
  public status: boolean = true,
  public incorrectRequest: boolean = false,
  public internalError: boolean = false,
  public incorrectDt: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return choose_sync_mode_resp.createchoose_sync_mode_resp(builder,
    this.status,
    this.incorrectRequest,
    this.internalError,
    this.incorrectDt
  );
}
}
