// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class delete_object {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):delete_object {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsdelete_object(bb:flatbuffers.ByteBuffer, obj?:delete_object):delete_object {
  return (obj || new delete_object()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsdelete_object(bb:flatbuffers.ByteBuffer, obj?:delete_object):delete_object {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new delete_object()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 *Название структуры, экземпляр которого нужно удалить
 */
nameStruct():string|null
nameStruct(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nameStruct(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nameObject():string|null
nameObject(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nameObject(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startdelete_object(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addNameStruct(builder:flatbuffers.Builder, nameStructOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameStructOffset, 0);
}

static addNameObject(builder:flatbuffers.Builder, nameObjectOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameObjectOffset, 0);
}

static enddelete_object(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createdelete_object(builder:flatbuffers.Builder, nameStructOffset:flatbuffers.Offset, nameObjectOffset:flatbuffers.Offset):flatbuffers.Offset {
  delete_object.startdelete_object(builder);
  delete_object.addNameStruct(builder, nameStructOffset);
  delete_object.addNameObject(builder, nameObjectOffset);
  return delete_object.enddelete_object(builder);
}

unpack(): delete_objectT {
  return new delete_objectT(
    this.nameStruct(),
    this.nameObject()
  );
}


unpackTo(_o: delete_objectT): void {
  _o.nameStruct = this.nameStruct();
  _o.nameObject = this.nameObject();
}
}

export class delete_objectT {
constructor(
  public nameStruct: string|Uint8Array|null = null,
  public nameObject: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const nameStruct = (this.nameStruct !== null ? builder.createString(this.nameStruct!) : 0);
  const nameObject = (this.nameObject !== null ? builder.createString(this.nameObject!) : 0);

  return delete_object.createdelete_object(builder,
    nameStruct,
    nameObject
  );
}
}
