// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 *Ответ
 */
export class join_system_resp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):join_system_resp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsjoin_system_resp(bb:flatbuffers.ByteBuffer, obj?:join_system_resp):join_system_resp {
  return (obj || new join_system_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsjoin_system_resp(bb:flatbuffers.ByteBuffer, obj?:join_system_resp):join_system_resp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new join_system_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 *Статус, true если нет ошибок
 */
status():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 *Необходимо восстановить состояние
 */
needRestoreState():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Некорректный запрос
 */
incorrectRequest():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Внутрення ошибка ПМ Брокер сообщений, дальнейшая работа невозможна
 */
internalError():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Модуль под таким именем уже присоединен
 */
moduleAlreadyJoin():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startjoin_system_resp(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addStatus(builder:flatbuffers.Builder, status:boolean) {
  builder.addFieldInt8(0, +status, +true);
}

static addNeedRestoreState(builder:flatbuffers.Builder, needRestoreState:boolean) {
  builder.addFieldInt8(1, +needRestoreState, +false);
}

static addIncorrectRequest(builder:flatbuffers.Builder, incorrectRequest:boolean) {
  builder.addFieldInt8(2, +incorrectRequest, +false);
}

static addInternalError(builder:flatbuffers.Builder, internalError:boolean) {
  builder.addFieldInt8(3, +internalError, +false);
}

static addModuleAlreadyJoin(builder:flatbuffers.Builder, moduleAlreadyJoin:boolean) {
  builder.addFieldInt8(4, +moduleAlreadyJoin, +false);
}

static endjoin_system_resp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createjoin_system_resp(builder:flatbuffers.Builder, status:boolean, needRestoreState:boolean, incorrectRequest:boolean, internalError:boolean, moduleAlreadyJoin:boolean):flatbuffers.Offset {
  join_system_resp.startjoin_system_resp(builder);
  join_system_resp.addStatus(builder, status);
  join_system_resp.addNeedRestoreState(builder, needRestoreState);
  join_system_resp.addIncorrectRequest(builder, incorrectRequest);
  join_system_resp.addInternalError(builder, internalError);
  join_system_resp.addModuleAlreadyJoin(builder, moduleAlreadyJoin);
  return join_system_resp.endjoin_system_resp(builder);
}

unpack(): join_system_respT {
  return new join_system_respT(
    this.status(),
    this.needRestoreState(),
    this.incorrectRequest(),
    this.internalError(),
    this.moduleAlreadyJoin()
  );
}


unpackTo(_o: join_system_respT): void {
  _o.status = this.status();
  _o.needRestoreState = this.needRestoreState();
  _o.incorrectRequest = this.incorrectRequest();
  _o.internalError = this.internalError();
  _o.moduleAlreadyJoin = this.moduleAlreadyJoin();
}
}

export class join_system_respT {
constructor(
  public status: boolean = true,
  public needRestoreState: boolean = false,
  public incorrectRequest: boolean = false,
  public internalError: boolean = false,
  public moduleAlreadyJoin: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return join_system_resp.createjoin_system_resp(builder,
    this.status,
    this.needRestoreState,
    this.incorrectRequest,
    this.internalError,
    this.moduleAlreadyJoin
  );
}
}
