// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Messages_type, unionToMessages_type, unionListToMessages_type } from '../../m-b/msg/messages_type';
import { choose_sync_mode, choose_sync_modeT } from '../../m-b/msg/choose_sync_mode';
import { choose_sync_mode_resp, choose_sync_mode_respT } from '../../m-b/msg/choose_sync_mode_resp';
import { create_object, create_objectT } from '../../m-b/msg/create_object';
import { create_object_resp, create_object_respT } from '../../m-b/msg/create_object_resp';
import { current_logical_time, current_logical_timeT } from '../../m-b/msg/current_logical_time';
import { current_logical_time_resp, current_logical_time_respT } from '../../m-b/msg/current_logical_time_resp';
import { delete_object, delete_objectT } from '../../m-b/msg/delete_object';
import { delete_object_resp, delete_object_respT } from '../../m-b/msg/delete_object_resp';
import { get_module_status, get_module_statusT } from '../../m-b/msg/get_module_status';
import { get_module_status_resp, get_module_status_respT } from '../../m-b/msg/get_module_status_resp';
import { get_sync_point, get_sync_pointT } from '../../m-b/msg/get_sync_point';
import { get_sync_point_resp, get_sync_point_respT } from '../../m-b/msg/get_sync_point_resp';
import { join_system, join_systemT } from '../../m-b/msg/join_system';
import { join_system_resp, join_system_respT } from '../../m-b/msg/join_system_resp';
import { joined_module_list, joined_module_listT } from '../../m-b/msg/joined_module_list';
import { joined_module_list_resp, joined_module_list_respT } from '../../m-b/msg/joined_module_list_resp';
import { module_data_info, module_data_infoT } from '../../m-b/msg/module_data_info';
import { module_data_info_resp, module_data_info_respT } from '../../m-b/msg/module_data_info_resp';
import { next_time, next_timeT } from '../../m-b/msg/next_time';
import { next_time_resp, next_time_respT } from '../../m-b/msg/next_time_resp';
import { publish_struct_info, publish_struct_infoT } from '../../m-b/msg/publish_struct_info';
import { publish_struct_info_resp, publish_struct_info_respT } from '../../m-b/msg/publish_struct_info_resp';
import { quit_from_system, quit_from_systemT } from '../../m-b/msg/quit_from_system';
import { quit_from_system_resp, quit_from_system_respT } from '../../m-b/msg/quit_from_system_resp';
import { reflect_attributes, reflect_attributesT } from '../../m-b/msg/reflect_attributes';
import { register_sync_point, register_sync_pointT } from '../../m-b/msg/register_sync_point';
import { register_sync_point_resp, register_sync_point_respT } from '../../m-b/msg/register_sync_point_resp';
import { request_from_mb_restore_state, request_from_mb_restore_stateT } from '../../m-b/msg/request_from_mb_restore_state';
import { request_from_mb_save_state, request_from_mb_save_stateT } from '../../m-b/msg/request_from_mb_save_state';
import { request_handle, request_handleT } from '../../m-b/msg/request_handle';
import { request_handle_resp, request_handle_respT } from '../../m-b/msg/request_handle_resp';
import { response_to_mb_restore_state_req, response_to_mb_restore_state_reqT } from '../../m-b/msg/response_to_mb_restore_state_req';
import { response_to_mb_save_state_req, response_to_mb_save_state_reqT } from '../../m-b/msg/response_to_mb_save_state_req';
import { subscribe_struct_info, subscribe_struct_infoT } from '../../m-b/msg/subscribe_struct_info';
import { subscribe_struct_info_resp, subscribe_struct_info_respT } from '../../m-b/msg/subscribe_struct_info_resp';
import { unpublish_struct, unpublish_structT } from '../../m-b/msg/unpublish_struct';
import { unpublish_struct_resp, unpublish_struct_respT } from '../../m-b/msg/unpublish_struct_resp';
import { unsubscribe_struct, unsubscribe_structT } from '../../m-b/msg/unsubscribe_struct';
import { unsubscribe_struct_resp, unsubscribe_struct_respT } from '../../m-b/msg/unsubscribe_struct_resp';
import { update_attrubutes, update_attrubutesT } from '../../m-b/msg/update_attrubutes';
import { update_attrubutes_resp, update_attrubutes_respT } from '../../m-b/msg/update_attrubutes_resp';
import { update_status, update_statusT } from '../../m-b/msg/update_status';
import { update_status_resp, update_status_respT } from '../../m-b/msg/update_status_resp';


export class Message {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Message {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

dataType():Messages_type {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Messages_type.NONE;
}

data<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDataType(builder:flatbuffers.Builder, dataType:Messages_type) {
  builder.addFieldInt8(0, dataType, Messages_type.NONE);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
}

static endMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createMessage(builder:flatbuffers.Builder, dataType:Messages_type, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  Message.startMessage(builder);
  Message.addDataType(builder, dataType);
  Message.addData(builder, dataOffset);
  return Message.endMessage(builder);
}

unpack(): MessageT {
  return new MessageT(
    this.dataType(),
    (() => {
      let temp = unionToMessages_type(this.dataType(), this.data.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: MessageT): void {
  _o.dataType = this.dataType();
  _o.data = (() => {
      let temp = unionToMessages_type(this.dataType(), this.data.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class MessageT {
constructor(
  public dataType: Messages_type = Messages_type.NONE,
  public data: choose_sync_modeT|choose_sync_mode_respT|create_objectT|create_object_respT|current_logical_timeT|current_logical_time_respT|delete_objectT|delete_object_respT|get_module_statusT|get_module_status_respT|get_sync_pointT|get_sync_point_respT|join_systemT|join_system_respT|joined_module_listT|joined_module_list_respT|module_data_infoT|module_data_info_respT|next_timeT|next_time_respT|publish_struct_infoT|publish_struct_info_respT|quit_from_systemT|quit_from_system_respT|reflect_attributesT|register_sync_pointT|register_sync_point_respT|request_from_mb_restore_stateT|request_from_mb_save_stateT|request_handleT|request_handle_respT|response_to_mb_restore_state_reqT|response_to_mb_save_state_reqT|subscribe_struct_infoT|subscribe_struct_info_respT|unpublish_structT|unpublish_struct_respT|unsubscribe_structT|unsubscribe_struct_respT|update_attrubutesT|update_attrubutes_respT|update_statusT|update_status_respT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const data = builder.createObjectOffset(this.data);

  return Message.createMessage(builder,
    this.dataType,
    data
  );
}
}
