// automatically generated by the FlatBuffers compiler, do not modify

import { choose_sync_mode, choose_sync_modeT } from '../../m-b/msg/choose_sync_mode';
import { choose_sync_mode_resp, choose_sync_mode_respT } from '../../m-b/msg/choose_sync_mode_resp';
import { create_object, create_objectT } from '../../m-b/msg/create_object';
import { create_object_resp, create_object_respT } from '../../m-b/msg/create_object_resp';
import { current_logical_time, current_logical_timeT } from '../../m-b/msg/current_logical_time';
import { current_logical_time_resp, current_logical_time_respT } from '../../m-b/msg/current_logical_time_resp';
import { delete_object, delete_objectT } from '../../m-b/msg/delete_object';
import { delete_object_resp, delete_object_respT } from '../../m-b/msg/delete_object_resp';
import { get_module_status, get_module_statusT } from '../../m-b/msg/get_module_status';
import { get_module_status_resp, get_module_status_respT } from '../../m-b/msg/get_module_status_resp';
import { get_sync_point, get_sync_pointT } from '../../m-b/msg/get_sync_point';
import { get_sync_point_resp, get_sync_point_respT } from '../../m-b/msg/get_sync_point_resp';
import { join_system, join_systemT } from '../../m-b/msg/join_system';
import { join_system_resp, join_system_respT } from '../../m-b/msg/join_system_resp';
import { joined_module_list, joined_module_listT } from '../../m-b/msg/joined_module_list';
import { joined_module_list_resp, joined_module_list_respT } from '../../m-b/msg/joined_module_list_resp';
import { module_data_info, module_data_infoT } from '../../m-b/msg/module_data_info';
import { module_data_info_resp, module_data_info_respT } from '../../m-b/msg/module_data_info_resp';
import { next_time, next_timeT } from '../../m-b/msg/next_time';
import { next_time_resp, next_time_respT } from '../../m-b/msg/next_time_resp';
import { publish_struct_info, publish_struct_infoT } from '../../m-b/msg/publish_struct_info';
import { publish_struct_info_resp, publish_struct_info_respT } from '../../m-b/msg/publish_struct_info_resp';
import { quit_from_system, quit_from_systemT } from '../../m-b/msg/quit_from_system';
import { quit_from_system_resp, quit_from_system_respT } from '../../m-b/msg/quit_from_system_resp';
import { reflect_attributes, reflect_attributesT } from '../../m-b/msg/reflect_attributes';
import { register_sync_point, register_sync_pointT } from '../../m-b/msg/register_sync_point';
import { register_sync_point_resp, register_sync_point_respT } from '../../m-b/msg/register_sync_point_resp';
import { request_from_mb_restore_state, request_from_mb_restore_stateT } from '../../m-b/msg/request_from_mb_restore_state';
import { request_from_mb_save_state, request_from_mb_save_stateT } from '../../m-b/msg/request_from_mb_save_state';
import { request_handle, request_handleT } from '../../m-b/msg/request_handle';
import { request_handle_resp, request_handle_respT } from '../../m-b/msg/request_handle_resp';
import { response_to_mb_restore_state_req, response_to_mb_restore_state_reqT } from '../../m-b/msg/response_to_mb_restore_state_req';
import { response_to_mb_save_state_req, response_to_mb_save_state_reqT } from '../../m-b/msg/response_to_mb_save_state_req';
import { subscribe_struct_info, subscribe_struct_infoT } from '../../m-b/msg/subscribe_struct_info';
import { subscribe_struct_info_resp, subscribe_struct_info_respT } from '../../m-b/msg/subscribe_struct_info_resp';
import { unpublish_struct, unpublish_structT } from '../../m-b/msg/unpublish_struct';
import { unpublish_struct_resp, unpublish_struct_respT } from '../../m-b/msg/unpublish_struct_resp';
import { unsubscribe_struct, unsubscribe_structT } from '../../m-b/msg/unsubscribe_struct';
import { unsubscribe_struct_resp, unsubscribe_struct_respT } from '../../m-b/msg/unsubscribe_struct_resp';
import { update_attrubutes, update_attrubutesT } from '../../m-b/msg/update_attrubutes';
import { update_attrubutes_resp, update_attrubutes_respT } from '../../m-b/msg/update_attrubutes_resp';
import { update_status, update_statusT } from '../../m-b/msg/update_status';
import { update_status_resp, update_status_respT } from '../../m-b/msg/update_status_resp';


export enum Messages_type{
  NONE = 0,
  join_system = 1,
  join_system_resp = 2,
  choose_sync_mode = 3,
  choose_sync_mode_resp = 4,
  publish_struct_info = 5,
  publish_struct_info_resp = 6,
  unpublish_struct = 7,
  unpublish_struct_resp = 8,
  subscribe_struct_info = 9,
  subscribe_struct_info_resp = 10,
  unsubscribe_struct = 11,
  unsubscribe_struct_resp = 12,
  next_time = 13,
  next_time_resp = 14,
  create_object = 15,
  create_object_resp = 16,
  delete_object = 17,
  delete_object_resp = 18,
  request_handle = 19,
  request_handle_resp = 20,
  quit_from_system = 21,
  quit_from_system_resp = 22,
  get_module_status = 23,
  get_module_status_resp = 24,
  update_attrubutes = 25,
  update_attrubutes_resp = 26,
  reflect_attributes = 27,
  update_status = 28,
  update_status_resp = 29,
  request_from_mb_save_state = 30,
  response_to_mb_save_state_req = 31,
  request_from_mb_restore_state = 32,
  response_to_mb_restore_state_req = 33,
  register_sync_point = 34,
  register_sync_point_resp = 35,
  get_sync_point = 36,
  get_sync_point_resp = 37,
  current_logical_time = 38,
  current_logical_time_resp = 39,
  joined_module_list = 40,
  joined_module_list_resp = 41,
  module_data_info = 42,
  module_data_info_resp = 43
}

export function unionToMessages_type(
  type: Messages_type,
  accessor: (obj:choose_sync_mode|choose_sync_mode_resp|create_object|create_object_resp|current_logical_time|current_logical_time_resp|delete_object|delete_object_resp|get_module_status|get_module_status_resp|get_sync_point|get_sync_point_resp|join_system|join_system_resp|joined_module_list|joined_module_list_resp|module_data_info|module_data_info_resp|next_time|next_time_resp|publish_struct_info|publish_struct_info_resp|quit_from_system|quit_from_system_resp|reflect_attributes|register_sync_point|register_sync_point_resp|request_from_mb_restore_state|request_from_mb_save_state|request_handle|request_handle_resp|response_to_mb_restore_state_req|response_to_mb_save_state_req|subscribe_struct_info|subscribe_struct_info_resp|unpublish_struct|unpublish_struct_resp|unsubscribe_struct|unsubscribe_struct_resp|update_attrubutes|update_attrubutes_resp|update_status|update_status_resp) => choose_sync_mode|choose_sync_mode_resp|create_object|create_object_resp|current_logical_time|current_logical_time_resp|delete_object|delete_object_resp|get_module_status|get_module_status_resp|get_sync_point|get_sync_point_resp|join_system|join_system_resp|joined_module_list|joined_module_list_resp|module_data_info|module_data_info_resp|next_time|next_time_resp|publish_struct_info|publish_struct_info_resp|quit_from_system|quit_from_system_resp|reflect_attributes|register_sync_point|register_sync_point_resp|request_from_mb_restore_state|request_from_mb_save_state|request_handle|request_handle_resp|response_to_mb_restore_state_req|response_to_mb_save_state_req|subscribe_struct_info|subscribe_struct_info_resp|unpublish_struct|unpublish_struct_resp|unsubscribe_struct|unsubscribe_struct_resp|update_attrubutes|update_attrubutes_resp|update_status|update_status_resp|null
): choose_sync_mode|choose_sync_mode_resp|create_object|create_object_resp|current_logical_time|current_logical_time_resp|delete_object|delete_object_resp|get_module_status|get_module_status_resp|get_sync_point|get_sync_point_resp|join_system|join_system_resp|joined_module_list|joined_module_list_resp|module_data_info|module_data_info_resp|next_time|next_time_resp|publish_struct_info|publish_struct_info_resp|quit_from_system|quit_from_system_resp|reflect_attributes|register_sync_point|register_sync_point_resp|request_from_mb_restore_state|request_from_mb_save_state|request_handle|request_handle_resp|response_to_mb_restore_state_req|response_to_mb_save_state_req|subscribe_struct_info|subscribe_struct_info_resp|unpublish_struct|unpublish_struct_resp|unsubscribe_struct|unsubscribe_struct_resp|update_attrubutes|update_attrubutes_resp|update_status|update_status_resp|null {
  switch(Messages_type[type]) {
    case 'NONE': return null; 
    case 'join_system': return accessor(new join_system())! as join_system;
    case 'join_system_resp': return accessor(new join_system_resp())! as join_system_resp;
    case 'choose_sync_mode': return accessor(new choose_sync_mode())! as choose_sync_mode;
    case 'choose_sync_mode_resp': return accessor(new choose_sync_mode_resp())! as choose_sync_mode_resp;
    case 'publish_struct_info': return accessor(new publish_struct_info())! as publish_struct_info;
    case 'publish_struct_info_resp': return accessor(new publish_struct_info_resp())! as publish_struct_info_resp;
    case 'unpublish_struct': return accessor(new unpublish_struct())! as unpublish_struct;
    case 'unpublish_struct_resp': return accessor(new unpublish_struct_resp())! as unpublish_struct_resp;
    case 'subscribe_struct_info': return accessor(new subscribe_struct_info())! as subscribe_struct_info;
    case 'subscribe_struct_info_resp': return accessor(new subscribe_struct_info_resp())! as subscribe_struct_info_resp;
    case 'unsubscribe_struct': return accessor(new unsubscribe_struct())! as unsubscribe_struct;
    case 'unsubscribe_struct_resp': return accessor(new unsubscribe_struct_resp())! as unsubscribe_struct_resp;
    case 'next_time': return accessor(new next_time())! as next_time;
    case 'next_time_resp': return accessor(new next_time_resp())! as next_time_resp;
    case 'create_object': return accessor(new create_object())! as create_object;
    case 'create_object_resp': return accessor(new create_object_resp())! as create_object_resp;
    case 'delete_object': return accessor(new delete_object())! as delete_object;
    case 'delete_object_resp': return accessor(new delete_object_resp())! as delete_object_resp;
    case 'request_handle': return accessor(new request_handle())! as request_handle;
    case 'request_handle_resp': return accessor(new request_handle_resp())! as request_handle_resp;
    case 'quit_from_system': return accessor(new quit_from_system())! as quit_from_system;
    case 'quit_from_system_resp': return accessor(new quit_from_system_resp())! as quit_from_system_resp;
    case 'get_module_status': return accessor(new get_module_status())! as get_module_status;
    case 'get_module_status_resp': return accessor(new get_module_status_resp())! as get_module_status_resp;
    case 'update_attrubutes': return accessor(new update_attrubutes())! as update_attrubutes;
    case 'update_attrubutes_resp': return accessor(new update_attrubutes_resp())! as update_attrubutes_resp;
    case 'reflect_attributes': return accessor(new reflect_attributes())! as reflect_attributes;
    case 'update_status': return accessor(new update_status())! as update_status;
    case 'update_status_resp': return accessor(new update_status_resp())! as update_status_resp;
    case 'request_from_mb_save_state': return accessor(new request_from_mb_save_state())! as request_from_mb_save_state;
    case 'response_to_mb_save_state_req': return accessor(new response_to_mb_save_state_req())! as response_to_mb_save_state_req;
    case 'request_from_mb_restore_state': return accessor(new request_from_mb_restore_state())! as request_from_mb_restore_state;
    case 'response_to_mb_restore_state_req': return accessor(new response_to_mb_restore_state_req())! as response_to_mb_restore_state_req;
    case 'register_sync_point': return accessor(new register_sync_point())! as register_sync_point;
    case 'register_sync_point_resp': return accessor(new register_sync_point_resp())! as register_sync_point_resp;
    case 'get_sync_point': return accessor(new get_sync_point())! as get_sync_point;
    case 'get_sync_point_resp': return accessor(new get_sync_point_resp())! as get_sync_point_resp;
    case 'current_logical_time': return accessor(new current_logical_time())! as current_logical_time;
    case 'current_logical_time_resp': return accessor(new current_logical_time_resp())! as current_logical_time_resp;
    case 'joined_module_list': return accessor(new joined_module_list())! as joined_module_list;
    case 'joined_module_list_resp': return accessor(new joined_module_list_resp())! as joined_module_list_resp;
    case 'module_data_info': return accessor(new module_data_info())! as module_data_info;
    case 'module_data_info_resp': return accessor(new module_data_info_resp())! as module_data_info_resp;
    default: return null;
  }
}

export function unionListToMessages_type(
  type: Messages_type, 
  accessor: (index: number, obj:choose_sync_mode|choose_sync_mode_resp|create_object|create_object_resp|current_logical_time|current_logical_time_resp|delete_object|delete_object_resp|get_module_status|get_module_status_resp|get_sync_point|get_sync_point_resp|join_system|join_system_resp|joined_module_list|joined_module_list_resp|module_data_info|module_data_info_resp|next_time|next_time_resp|publish_struct_info|publish_struct_info_resp|quit_from_system|quit_from_system_resp|reflect_attributes|register_sync_point|register_sync_point_resp|request_from_mb_restore_state|request_from_mb_save_state|request_handle|request_handle_resp|response_to_mb_restore_state_req|response_to_mb_save_state_req|subscribe_struct_info|subscribe_struct_info_resp|unpublish_struct|unpublish_struct_resp|unsubscribe_struct|unsubscribe_struct_resp|update_attrubutes|update_attrubutes_resp|update_status|update_status_resp) => choose_sync_mode|choose_sync_mode_resp|create_object|create_object_resp|current_logical_time|current_logical_time_resp|delete_object|delete_object_resp|get_module_status|get_module_status_resp|get_sync_point|get_sync_point_resp|join_system|join_system_resp|joined_module_list|joined_module_list_resp|module_data_info|module_data_info_resp|next_time|next_time_resp|publish_struct_info|publish_struct_info_resp|quit_from_system|quit_from_system_resp|reflect_attributes|register_sync_point|register_sync_point_resp|request_from_mb_restore_state|request_from_mb_save_state|request_handle|request_handle_resp|response_to_mb_restore_state_req|response_to_mb_save_state_req|subscribe_struct_info|subscribe_struct_info_resp|unpublish_struct|unpublish_struct_resp|unsubscribe_struct|unsubscribe_struct_resp|update_attrubutes|update_attrubutes_resp|update_status|update_status_resp|null, 
  index: number
): choose_sync_mode|choose_sync_mode_resp|create_object|create_object_resp|current_logical_time|current_logical_time_resp|delete_object|delete_object_resp|get_module_status|get_module_status_resp|get_sync_point|get_sync_point_resp|join_system|join_system_resp|joined_module_list|joined_module_list_resp|module_data_info|module_data_info_resp|next_time|next_time_resp|publish_struct_info|publish_struct_info_resp|quit_from_system|quit_from_system_resp|reflect_attributes|register_sync_point|register_sync_point_resp|request_from_mb_restore_state|request_from_mb_save_state|request_handle|request_handle_resp|response_to_mb_restore_state_req|response_to_mb_save_state_req|subscribe_struct_info|subscribe_struct_info_resp|unpublish_struct|unpublish_struct_resp|unsubscribe_struct|unsubscribe_struct_resp|update_attrubutes|update_attrubutes_resp|update_status|update_status_resp|null {
  switch(Messages_type[type]) {
    case 'NONE': return null; 
    case 'join_system': return accessor(index, new join_system())! as join_system;
    case 'join_system_resp': return accessor(index, new join_system_resp())! as join_system_resp;
    case 'choose_sync_mode': return accessor(index, new choose_sync_mode())! as choose_sync_mode;
    case 'choose_sync_mode_resp': return accessor(index, new choose_sync_mode_resp())! as choose_sync_mode_resp;
    case 'publish_struct_info': return accessor(index, new publish_struct_info())! as publish_struct_info;
    case 'publish_struct_info_resp': return accessor(index, new publish_struct_info_resp())! as publish_struct_info_resp;
    case 'unpublish_struct': return accessor(index, new unpublish_struct())! as unpublish_struct;
    case 'unpublish_struct_resp': return accessor(index, new unpublish_struct_resp())! as unpublish_struct_resp;
    case 'subscribe_struct_info': return accessor(index, new subscribe_struct_info())! as subscribe_struct_info;
    case 'subscribe_struct_info_resp': return accessor(index, new subscribe_struct_info_resp())! as subscribe_struct_info_resp;
    case 'unsubscribe_struct': return accessor(index, new unsubscribe_struct())! as unsubscribe_struct;
    case 'unsubscribe_struct_resp': return accessor(index, new unsubscribe_struct_resp())! as unsubscribe_struct_resp;
    case 'next_time': return accessor(index, new next_time())! as next_time;
    case 'next_time_resp': return accessor(index, new next_time_resp())! as next_time_resp;
    case 'create_object': return accessor(index, new create_object())! as create_object;
    case 'create_object_resp': return accessor(index, new create_object_resp())! as create_object_resp;
    case 'delete_object': return accessor(index, new delete_object())! as delete_object;
    case 'delete_object_resp': return accessor(index, new delete_object_resp())! as delete_object_resp;
    case 'request_handle': return accessor(index, new request_handle())! as request_handle;
    case 'request_handle_resp': return accessor(index, new request_handle_resp())! as request_handle_resp;
    case 'quit_from_system': return accessor(index, new quit_from_system())! as quit_from_system;
    case 'quit_from_system_resp': return accessor(index, new quit_from_system_resp())! as quit_from_system_resp;
    case 'get_module_status': return accessor(index, new get_module_status())! as get_module_status;
    case 'get_module_status_resp': return accessor(index, new get_module_status_resp())! as get_module_status_resp;
    case 'update_attrubutes': return accessor(index, new update_attrubutes())! as update_attrubutes;
    case 'update_attrubutes_resp': return accessor(index, new update_attrubutes_resp())! as update_attrubutes_resp;
    case 'reflect_attributes': return accessor(index, new reflect_attributes())! as reflect_attributes;
    case 'update_status': return accessor(index, new update_status())! as update_status;
    case 'update_status_resp': return accessor(index, new update_status_resp())! as update_status_resp;
    case 'request_from_mb_save_state': return accessor(index, new request_from_mb_save_state())! as request_from_mb_save_state;
    case 'response_to_mb_save_state_req': return accessor(index, new response_to_mb_save_state_req())! as response_to_mb_save_state_req;
    case 'request_from_mb_restore_state': return accessor(index, new request_from_mb_restore_state())! as request_from_mb_restore_state;
    case 'response_to_mb_restore_state_req': return accessor(index, new response_to_mb_restore_state_req())! as response_to_mb_restore_state_req;
    case 'register_sync_point': return accessor(index, new register_sync_point())! as register_sync_point;
    case 'register_sync_point_resp': return accessor(index, new register_sync_point_resp())! as register_sync_point_resp;
    case 'get_sync_point': return accessor(index, new get_sync_point())! as get_sync_point;
    case 'get_sync_point_resp': return accessor(index, new get_sync_point_resp())! as get_sync_point_resp;
    case 'current_logical_time': return accessor(index, new current_logical_time())! as current_logical_time;
    case 'current_logical_time_resp': return accessor(index, new current_logical_time_resp())! as current_logical_time_resp;
    case 'joined_module_list': return accessor(index, new joined_module_list())! as joined_module_list;
    case 'joined_module_list_resp': return accessor(index, new joined_module_list_resp())! as joined_module_list_resp;
    case 'module_data_info': return accessor(index, new module_data_info())! as module_data_info;
    case 'module_data_info_resp': return accessor(index, new module_data_info_resp())! as module_data_info_resp;
    default: return null;
  }
}

