// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 *Ответ
 */
export class register_sync_point_resp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):register_sync_point_resp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsregister_sync_point_resp(bb:flatbuffers.ByteBuffer, obj?:register_sync_point_resp):register_sync_point_resp {
  return (obj || new register_sync_point_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsregister_sync_point_resp(bb:flatbuffers.ByteBuffer, obj?:register_sync_point_resp):register_sync_point_resp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new register_sync_point_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 *Статус, true если нет ошибок
 */
status():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 *Некорректный запрос
 */
incorrectRequest():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Внутрення ошибка ПМ Брокер сообщений, дальнейшая работа невозможна
 */
internalError():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Точка синхронизации с таким именем уже существует
 */
pointAlreadyExists():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startregister_sync_point_resp(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addStatus(builder:flatbuffers.Builder, status:boolean) {
  builder.addFieldInt8(0, +status, +true);
}

static addIncorrectRequest(builder:flatbuffers.Builder, incorrectRequest:boolean) {
  builder.addFieldInt8(1, +incorrectRequest, +false);
}

static addInternalError(builder:flatbuffers.Builder, internalError:boolean) {
  builder.addFieldInt8(2, +internalError, +false);
}

static addPointAlreadyExists(builder:flatbuffers.Builder, pointAlreadyExists:boolean) {
  builder.addFieldInt8(3, +pointAlreadyExists, +false);
}

static endregister_sync_point_resp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createregister_sync_point_resp(builder:flatbuffers.Builder, status:boolean, incorrectRequest:boolean, internalError:boolean, pointAlreadyExists:boolean):flatbuffers.Offset {
  register_sync_point_resp.startregister_sync_point_resp(builder);
  register_sync_point_resp.addStatus(builder, status);
  register_sync_point_resp.addIncorrectRequest(builder, incorrectRequest);
  register_sync_point_resp.addInternalError(builder, internalError);
  register_sync_point_resp.addPointAlreadyExists(builder, pointAlreadyExists);
  return register_sync_point_resp.endregister_sync_point_resp(builder);
}

unpack(): register_sync_point_respT {
  return new register_sync_point_respT(
    this.status(),
    this.incorrectRequest(),
    this.internalError(),
    this.pointAlreadyExists()
  );
}


unpackTo(_o: register_sync_point_respT): void {
  _o.status = this.status();
  _o.incorrectRequest = this.incorrectRequest();
  _o.internalError = this.internalError();
  _o.pointAlreadyExists = this.pointAlreadyExists();
}
}

export class register_sync_point_respT {
constructor(
  public status: boolean = true,
  public incorrectRequest: boolean = false,
  public internalError: boolean = false,
  public pointAlreadyExists: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return register_sync_point_resp.createregister_sync_point_resp(builder,
    this.status,
    this.incorrectRequest,
    this.internalError,
    this.pointAlreadyExists
  );
}
}
