// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class request_from_mb_restore_state {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):request_from_mb_restore_state {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsrequest_from_mb_restore_state(bb:flatbuffers.ByteBuffer, obj?:request_from_mb_restore_state):request_from_mb_restore_state {
  return (obj || new request_from_mb_restore_state()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsrequest_from_mb_restore_state(bb:flatbuffers.ByteBuffer, obj?:request_from_mb_restore_state):request_from_mb_restore_state {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new request_from_mb_restore_state()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

needRestoreState():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

static startrequest_from_mb_restore_state(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addNeedRestoreState(builder:flatbuffers.Builder, needRestoreState:boolean) {
  builder.addFieldInt8(0, +needRestoreState, +true);
}

static endrequest_from_mb_restore_state(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createrequest_from_mb_restore_state(builder:flatbuffers.Builder, needRestoreState:boolean):flatbuffers.Offset {
  request_from_mb_restore_state.startrequest_from_mb_restore_state(builder);
  request_from_mb_restore_state.addNeedRestoreState(builder, needRestoreState);
  return request_from_mb_restore_state.endrequest_from_mb_restore_state(builder);
}

unpack(): request_from_mb_restore_stateT {
  return new request_from_mb_restore_stateT(
    this.needRestoreState()
  );
}


unpackTo(_o: request_from_mb_restore_stateT): void {
  _o.needRestoreState = this.needRestoreState();
}
}

export class request_from_mb_restore_stateT {
constructor(
  public needRestoreState: boolean = true
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return request_from_mb_restore_state.createrequest_from_mb_restore_state(builder,
    this.needRestoreState
  );
}
}
