// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class response_to_mb_restore_state_req {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):response_to_mb_restore_state_req {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsresponse_to_mb_restore_state_req(bb:flatbuffers.ByteBuffer, obj?:response_to_mb_restore_state_req):response_to_mb_restore_state_req {
  return (obj || new response_to_mb_restore_state_req()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsresponse_to_mb_restore_state_req(bb:flatbuffers.ByteBuffer, obj?:response_to_mb_restore_state_req):response_to_mb_restore_state_req {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new response_to_mb_restore_state_req()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * true Запрос принят
 */
requestAccepted():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * true ПМ не может восстановить свое состояние
 */
cannotRestoreState():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startresponse_to_mb_restore_state_req(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRequestAccepted(builder:flatbuffers.Builder, requestAccepted:boolean) {
  builder.addFieldInt8(0, +requestAccepted, +false);
}

static addCannotRestoreState(builder:flatbuffers.Builder, cannotRestoreState:boolean) {
  builder.addFieldInt8(1, +cannotRestoreState, +false);
}

static endresponse_to_mb_restore_state_req(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createresponse_to_mb_restore_state_req(builder:flatbuffers.Builder, requestAccepted:boolean, cannotRestoreState:boolean):flatbuffers.Offset {
  response_to_mb_restore_state_req.startresponse_to_mb_restore_state_req(builder);
  response_to_mb_restore_state_req.addRequestAccepted(builder, requestAccepted);
  response_to_mb_restore_state_req.addCannotRestoreState(builder, cannotRestoreState);
  return response_to_mb_restore_state_req.endresponse_to_mb_restore_state_req(builder);
}

unpack(): response_to_mb_restore_state_reqT {
  return new response_to_mb_restore_state_reqT(
    this.requestAccepted(),
    this.cannotRestoreState()
  );
}


unpackTo(_o: response_to_mb_restore_state_reqT): void {
  _o.requestAccepted = this.requestAccepted();
  _o.cannotRestoreState = this.cannotRestoreState();
}
}

export class response_to_mb_restore_state_reqT {
constructor(
  public requestAccepted: boolean = false,
  public cannotRestoreState: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return response_to_mb_restore_state_req.createresponse_to_mb_restore_state_req(builder,
    this.requestAccepted,
    this.cannotRestoreState
  );
}
}
