// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 *Ответ
 */
export class subscribe_struct_info_resp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):subscribe_struct_info_resp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAssubscribe_struct_info_resp(bb:flatbuffers.ByteBuffer, obj?:subscribe_struct_info_resp):subscribe_struct_info_resp {
  return (obj || new subscribe_struct_info_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAssubscribe_struct_info_resp(bb:flatbuffers.ByteBuffer, obj?:subscribe_struct_info_resp):subscribe_struct_info_resp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new subscribe_struct_info_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 *Статус, true если нет ошибок
 */
status():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 *Некорректный запрос
 */
incorrectRequest():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Внутрення ошибка ПМ Брокер сообщений, дальнейшая работа невозможна
 */
internalError():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Дескриптор структуры, которая была указана в запросе
 */
structHandle():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

/**
 *Дескриптор экземпляра структуры, который был указан в запросе
 */
objectHandle():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

fieldsHandle(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

fieldsHandleLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

fieldsHandleArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startsubscribe_struct_info_resp(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addStatus(builder:flatbuffers.Builder, status:boolean) {
  builder.addFieldInt8(0, +status, +true);
}

static addIncorrectRequest(builder:flatbuffers.Builder, incorrectRequest:boolean) {
  builder.addFieldInt8(1, +incorrectRequest, +false);
}

static addInternalError(builder:flatbuffers.Builder, internalError:boolean) {
  builder.addFieldInt8(2, +internalError, +false);
}

static addStructHandle(builder:flatbuffers.Builder, structHandle:number) {
  builder.addFieldInt8(3, structHandle, 0);
}

static addObjectHandle(builder:flatbuffers.Builder, objectHandle:number) {
  builder.addFieldInt8(4, objectHandle, 0);
}

static addFieldsHandle(builder:flatbuffers.Builder, fieldsHandleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, fieldsHandleOffset, 0);
}

static createFieldsHandleVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startFieldsHandleVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endsubscribe_struct_info_resp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createsubscribe_struct_info_resp(builder:flatbuffers.Builder, status:boolean, incorrectRequest:boolean, internalError:boolean, structHandle:number, objectHandle:number, fieldsHandleOffset:flatbuffers.Offset):flatbuffers.Offset {
  subscribe_struct_info_resp.startsubscribe_struct_info_resp(builder);
  subscribe_struct_info_resp.addStatus(builder, status);
  subscribe_struct_info_resp.addIncorrectRequest(builder, incorrectRequest);
  subscribe_struct_info_resp.addInternalError(builder, internalError);
  subscribe_struct_info_resp.addStructHandle(builder, structHandle);
  subscribe_struct_info_resp.addObjectHandle(builder, objectHandle);
  subscribe_struct_info_resp.addFieldsHandle(builder, fieldsHandleOffset);
  return subscribe_struct_info_resp.endsubscribe_struct_info_resp(builder);
}

unpack(): subscribe_struct_info_respT {
  return new subscribe_struct_info_respT(
    this.status(),
    this.incorrectRequest(),
    this.internalError(),
    this.structHandle(),
    this.objectHandle(),
    this.bb!.createScalarList(this.fieldsHandle.bind(this), this.fieldsHandleLength())
  );
}


unpackTo(_o: subscribe_struct_info_respT): void {
  _o.status = this.status();
  _o.incorrectRequest = this.incorrectRequest();
  _o.internalError = this.internalError();
  _o.structHandle = this.structHandle();
  _o.objectHandle = this.objectHandle();
  _o.fieldsHandle = this.bb!.createScalarList(this.fieldsHandle.bind(this), this.fieldsHandleLength());
}
}

export class subscribe_struct_info_respT {
constructor(
  public status: boolean = true,
  public incorrectRequest: boolean = false,
  public internalError: boolean = false,
  public structHandle: number = 0,
  public objectHandle: number = 0,
  public fieldsHandle: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const fieldsHandle = subscribe_struct_info_resp.createFieldsHandleVector(builder, this.fieldsHandle);

  return subscribe_struct_info_resp.createsubscribe_struct_info_resp(builder,
    this.status,
    this.incorrectRequest,
    this.internalError,
    this.structHandle,
    this.objectHandle,
    fieldsHandle
  );
}
}
