// automatically generated by the FlatBuffers compiler, do not modify

export enum sync_mode{
  /**
   *Асинхронный режим работы
   */
  async = 0,

  /**
   * Режим временного регулирования
   */
  time_regulation = 1,

  /**
   *Режим временного сдерживания
   */
  time_constrained = 2
}

