// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class unpublish_struct_resp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):unpublish_struct_resp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsunpublish_struct_resp(bb:flatbuffers.ByteBuffer, obj?:unpublish_struct_resp):unpublish_struct_resp {
  return (obj || new unpublish_struct_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsunpublish_struct_resp(bb:flatbuffers.ByteBuffer, obj?:unpublish_struct_resp):unpublish_struct_resp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new unpublish_struct_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

incorrectRequest():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

internalError():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startunpublish_struct_resp(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStatus(builder:flatbuffers.Builder, status:boolean) {
  builder.addFieldInt8(0, +status, +true);
}

static addIncorrectRequest(builder:flatbuffers.Builder, incorrectRequest:boolean) {
  builder.addFieldInt8(1, +incorrectRequest, +false);
}

static addInternalError(builder:flatbuffers.Builder, internalError:boolean) {
  builder.addFieldInt8(2, +internalError, +false);
}

static endunpublish_struct_resp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createunpublish_struct_resp(builder:flatbuffers.Builder, status:boolean, incorrectRequest:boolean, internalError:boolean):flatbuffers.Offset {
  unpublish_struct_resp.startunpublish_struct_resp(builder);
  unpublish_struct_resp.addStatus(builder, status);
  unpublish_struct_resp.addIncorrectRequest(builder, incorrectRequest);
  unpublish_struct_resp.addInternalError(builder, internalError);
  return unpublish_struct_resp.endunpublish_struct_resp(builder);
}

unpack(): unpublish_struct_respT {
  return new unpublish_struct_respT(
    this.status(),
    this.incorrectRequest(),
    this.internalError()
  );
}


unpackTo(_o: unpublish_struct_respT): void {
  _o.status = this.status();
  _o.incorrectRequest = this.incorrectRequest();
  _o.internalError = this.internalError();
}
}

export class unpublish_struct_respT {
constructor(
  public status: boolean = true,
  public incorrectRequest: boolean = false,
  public internalError: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return unpublish_struct_resp.createunpublish_struct_resp(builder,
    this.status,
    this.incorrectRequest,
    this.internalError
  );
}
}
