// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class unsubscribe_struct {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):unsubscribe_struct {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsunsubscribe_struct(bb:flatbuffers.ByteBuffer, obj?:unsubscribe_struct):unsubscribe_struct {
  return (obj || new unsubscribe_struct()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsunsubscribe_struct(bb:flatbuffers.ByteBuffer, obj?:unsubscribe_struct):unsubscribe_struct {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new unsubscribe_struct()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 *Название структуры от которой нужно отписаться
 */
structName():string|null
structName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
structName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 *Название экземпляра структуры от которого нужно отписаться
 */
objectName():string|null
objectName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 *Поля структуры от которых нужно отписаться
 */
fields(index: number):string
fields(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
fields(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

fieldsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startunsubscribe_struct(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStructName(builder:flatbuffers.Builder, structNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, structNameOffset, 0);
}

static addObjectName(builder:flatbuffers.Builder, objectNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, objectNameOffset, 0);
}

static addFields(builder:flatbuffers.Builder, fieldsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, fieldsOffset, 0);
}

static createFieldsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFieldsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endunsubscribe_struct(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createunsubscribe_struct(builder:flatbuffers.Builder, structNameOffset:flatbuffers.Offset, objectNameOffset:flatbuffers.Offset, fieldsOffset:flatbuffers.Offset):flatbuffers.Offset {
  unsubscribe_struct.startunsubscribe_struct(builder);
  unsubscribe_struct.addStructName(builder, structNameOffset);
  unsubscribe_struct.addObjectName(builder, objectNameOffset);
  unsubscribe_struct.addFields(builder, fieldsOffset);
  return unsubscribe_struct.endunsubscribe_struct(builder);
}

unpack(): unsubscribe_structT {
  return new unsubscribe_structT(
    this.structName(),
    this.objectName(),
    this.bb!.createScalarList(this.fields.bind(this), this.fieldsLength())
  );
}


unpackTo(_o: unsubscribe_structT): void {
  _o.structName = this.structName();
  _o.objectName = this.objectName();
  _o.fields = this.bb!.createScalarList(this.fields.bind(this), this.fieldsLength());
}
}

export class unsubscribe_structT {
constructor(
  public structName: string|Uint8Array|null = null,
  public objectName: string|Uint8Array|null = null,
  public fields: (string)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const structName = (this.structName !== null ? builder.createString(this.structName!) : 0);
  const objectName = (this.objectName !== null ? builder.createString(this.objectName!) : 0);
  const fields = unsubscribe_struct.createFieldsVector(builder, builder.createObjectOffsetList(this.fields));

  return unsubscribe_struct.createunsubscribe_struct(builder,
    structName,
    objectName,
    fields
  );
}
}
