// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 *Ответ
 */
export class unsubscribe_struct_resp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):unsubscribe_struct_resp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsunsubscribe_struct_resp(bb:flatbuffers.ByteBuffer, obj?:unsubscribe_struct_resp):unsubscribe_struct_resp {
  return (obj || new unsubscribe_struct_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsunsubscribe_struct_resp(bb:flatbuffers.ByteBuffer, obj?:unsubscribe_struct_resp):unsubscribe_struct_resp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new unsubscribe_struct_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 *Статус, true если нет ошибок
 */
status():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 *Некорректный запрос
 */
incorrectRequest():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *Внутрення ошибка ПМ Брокер сообщений, дальнейшая работа невозможна
 */
internalError():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startunsubscribe_struct_resp(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStatus(builder:flatbuffers.Builder, status:boolean) {
  builder.addFieldInt8(0, +status, +true);
}

static addIncorrectRequest(builder:flatbuffers.Builder, incorrectRequest:boolean) {
  builder.addFieldInt8(1, +incorrectRequest, +false);
}

static addInternalError(builder:flatbuffers.Builder, internalError:boolean) {
  builder.addFieldInt8(2, +internalError, +false);
}

static endunsubscribe_struct_resp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createunsubscribe_struct_resp(builder:flatbuffers.Builder, status:boolean, incorrectRequest:boolean, internalError:boolean):flatbuffers.Offset {
  unsubscribe_struct_resp.startunsubscribe_struct_resp(builder);
  unsubscribe_struct_resp.addStatus(builder, status);
  unsubscribe_struct_resp.addIncorrectRequest(builder, incorrectRequest);
  unsubscribe_struct_resp.addInternalError(builder, internalError);
  return unsubscribe_struct_resp.endunsubscribe_struct_resp(builder);
}

unpack(): unsubscribe_struct_respT {
  return new unsubscribe_struct_respT(
    this.status(),
    this.incorrectRequest(),
    this.internalError()
  );
}


unpackTo(_o: unsubscribe_struct_respT): void {
  _o.status = this.status();
  _o.incorrectRequest = this.incorrectRequest();
  _o.internalError = this.internalError();
}
}

export class unsubscribe_struct_respT {
constructor(
  public status: boolean = true,
  public incorrectRequest: boolean = false,
  public internalError: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return unsubscribe_struct_resp.createunsubscribe_struct_resp(builder,
    this.status,
    this.incorrectRequest,
    this.internalError
  );
}
}
