// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 *Ответ
 */
export class update_status_resp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):update_status_resp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsupdate_status_resp(bb:flatbuffers.ByteBuffer, obj?:update_status_resp):update_status_resp {
  return (obj || new update_status_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsupdate_status_resp(bb:flatbuffers.ByteBuffer, obj?:update_status_resp):update_status_resp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new update_status_resp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 *статус, true если нет ошибок
 */
status():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 * некорректный запрос
 */
incorrectRequest():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 *внутрення ошибка ПМ Брокер сообщений, дальнейшая работа невозможна
 */
internalError():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startupdate_status_resp(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStatus(builder:flatbuffers.Builder, status:boolean) {
  builder.addFieldInt8(0, +status, +true);
}

static addIncorrectRequest(builder:flatbuffers.Builder, incorrectRequest:boolean) {
  builder.addFieldInt8(1, +incorrectRequest, +false);
}

static addInternalError(builder:flatbuffers.Builder, internalError:boolean) {
  builder.addFieldInt8(2, +internalError, +false);
}

static endupdate_status_resp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createupdate_status_resp(builder:flatbuffers.Builder, status:boolean, incorrectRequest:boolean, internalError:boolean):flatbuffers.Offset {
  update_status_resp.startupdate_status_resp(builder);
  update_status_resp.addStatus(builder, status);
  update_status_resp.addIncorrectRequest(builder, incorrectRequest);
  update_status_resp.addInternalError(builder, internalError);
  return update_status_resp.endupdate_status_resp(builder);
}

unpack(): update_status_respT {
  return new update_status_respT(
    this.status(),
    this.incorrectRequest(),
    this.internalError()
  );
}


unpackTo(_o: update_status_respT): void {
  _o.status = this.status();
  _o.incorrectRequest = this.incorrectRequest();
  _o.internalError = this.internalError();
}
}

export class update_status_respT {
constructor(
  public status: boolean = true,
  public incorrectRequest: boolean = false,
  public internalError: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return update_status_resp.createupdate_status_resp(builder,
    this.status,
    this.incorrectRequest,
    this.internalError
  );
}
}
